import pytest
from schemas.event import Event, EventProperties
from schemas.story import Story


@pytest.fixture
def sample_events():
    return [
        Event(
            event="$input",
            properties=EventProperties(
                distinct_id="user_12345",
                session_id="session_67890",
                journey_id="journey_001",
                current_url="https://example.com/login",
                host="example.com",
                pathname="/login",
                browser="Chrome",
                device="Desktop",
                screen_height=1080,
                screen_width=1920,
                event_type="input",
                element_type="input",
                element_text="",
                element_attributes=dict(
                    id="email",
                    type="email"
                )
            ),
            timestamp="2024-12-16T10:00:00Z"
        ),
        Event(
            event="$input",
            properties=EventProperties(
                distinct_id="user_12345",
                session_id="session_67890",
                journey_id="journey_001",
                current_url="https://example.com/login",
                host="example.com",
                pathname="/login",
                browser="Chrome",
                device="Desktop",
                screen_height=1080,
                screen_width=1920,
                event_type="input",
                element_type="input",
                element_text="",
                element_attributes=dict(
                    id="password",
                    type="password"
                )
            ),
            timestamp="2024-12-16T10:00:15Z"
        ),
        Event(
            event="$click",
            properties=EventProperties(
                distinct_id="user_12345",
                session_id="session_67890",
                journey_id="journey_001",
                current_url="https://example.com/login",
                host="example.com",
                pathname="/login",
                browser="Chrome",
                device="Desktop",
                screen_height=1080,
                screen_width=1920,
                event_type="click",
                element_type="button",
                element_text="Log In",
                element_attributes=dict(
                    id="login-button",
                )
            ),
            timestamp="2024-12-16T10:00:30Z"
        ),
        Event(
            event="$api-call",
            properties=EventProperties(
                distinct_id="user_12345",
                session_id="session_67890",
                journey_id="journey_001",
                current_url="https://example.com/login",
                host="example.com",
                pathname="/login",
                browser="Chrome",
                device="Desktop",
                screen_height=1080,
                screen_width=1920,
                event_type="",
                element_type="",
                element_text="",
                element_attributes=dict(
                    api_url="https://api.example.com/login",
                    method="POST",
                    status="200",
                )
            ),
            timestamp="2024-12-16T10:00:35Z"
        ),
        Event(
            event="$navigation",
            properties=EventProperties(
                distinct_id="user_12345",
                session_id="session_67890",
                journey_id="journey_001",
                current_url="https://example.com/profile",
                host="example.com",
                pathname="/profile",
                browser="Chrome",
                device="Desktop",
                screen_height=1080,
                screen_width=1920,
                event_type="navigation",
                element_type="",
                element_text="",
                element_attributes=None
            ),
            timestamp="2024-12-16T10:00:40Z"
        ),
        Event(
            event="$input",
            properties=EventProperties(
                distinct_id="user_12345",
                session_id="session_67890",
                journey_id="journey_001",
                current_url="https://example.com/profile",
                host="example.com",
                pathname="/profile",
                browser="Chrome",
                device="Desktop",
                screen_height=1080,
                screen_width=1920,
                event_type="input",
                element_type="input",
                element_text="",
                element_attributes=dict(
                    id="display-name",
                    type="text"
                )
            ),
            timestamp="2024-12-16T10:00:60Z"
        ),
        Event(
            event="$click",
            properties=EventProperties(
                distinct_id="user_12345",
                session_id="session_67890",
                journey_id="journey_001",
                current_url="https://example.com/profile",
                host="example.com",
                pathname="/profile",
                browser="Chrome",
                device="Desktop",
                screen_height=1080,
                screen_width=1920,
                event_type="click",
                element_type="button",
                element_text="Save",
                element_attributes=dict(
                    id="save-profile",
                )
            ),
            timestamp="2024-12-16T10:00:90Z"
        ),
        Event(
            event="$api-call",
            properties=EventProperties(
                distinct_id="user_12345",
                session_id="session_67890",
                journey_id="journey_001",
                current_url="https://example.com/profile",
                host="example.com",
                pathname="/profile",
                browser="Chrome",
                device="Desktop",
                screen_height=1080,
                screen_width=1920,
                event_type="",
                element_type="",
                element_text="",
                element_attributes=dict(
                    api_url="https://api.example.com/profile",
                    method="PUT",
                    status="200",
                )
            ),
            timestamp="2024-12-16T10:00:95Z"
        ),
    ]


@pytest.fixture
def sample_story():
    return Story(
        name='login Log In',
        actions=[
            Event(
                event="$input",
                properties=EventProperties(
                    distinct_id="user_12345",
                    session_id="session_67890",
                    journey_id="journey_001",
                    current_url="https://example.com/login",
                    host="example.com",
                    pathname="/login",
                    browser="Chrome",
                    device="Desktop",
                    screen_height=1080,
                    screen_width=1920,
                    event_type="input",
                    element_type="input",
                    element_text="",
                    element_attributes=dict(
                        id="email",
                        type="email"
                    )
                ),
                timestamp="2024-12-16T10:00:00Z"
            ),
            Event(
                event="$input",
                properties=EventProperties(
                    distinct_id="user_12345",
                    session_id="session_67890",
                    journey_id="journey_001",
                    current_url="https://example.com/login",
                    host="example.com",
                    pathname="/login",
                    browser="Chrome",
                    device="Desktop",
                    screen_height=1080,
                    screen_width=1920,
                    event_type="input",
                    element_type="input",
                    element_text="",
                    element_attributes=dict(
                        id="password",
                        type="password"
                    )
                ),
                timestamp="2024-12-16T10:00:15Z"
            ),
            Event(
                event="$click",
                properties=EventProperties(
                    distinct_id="user_12345",
                    session_id="session_67890",
                    journey_id="journey_001",
                    current_url="https://example.com/login",
                    host="example.com",
                    pathname="/login",
                    browser="Chrome",
                    device="Desktop",
                    screen_height=1080,
                    screen_width=1920,
                    event_type="click",
                    element_type="button",
                    element_text="Log In",
                    element_attributes=dict(
                        id="login-button",
                    )
                ),
                timestamp="2024-12-16T10:00:30Z"
            ),
            Event(
                event="$api-call",
                properties=EventProperties(
                    distinct_id="user_12345",
                    session_id="session_67890",
                    journey_id="journey_001",
                    current_url="https://example.com/login",
                    host="example.com",
                    pathname="/login",
                    browser="Chrome",
                    device="Desktop",
                    screen_height=1080,
                    screen_width=1920,
                    event_type="",
                    element_type="",
                    element_text="",
                    element_attributes=dict(
                        api_url="https://api.example.com/login",
                        method="POST",
                        status="200",
                    )
                ),
                timestamp="2024-12-16T10:00:35Z"
            ),
            Event(
                event="$navigation",
                properties=EventProperties(
                    distinct_id="user_12345",
                    session_id="session_67890",
                    journey_id="journey_001",
                    current_url="https://example.com/profile",
                    host="example.com",
                    pathname="/profile",
                    browser="Chrome",
                    device="Desktop",
                    screen_height=1080,
                    screen_width=1920,
                    event_type="navigation",
                    element_type="",
                    element_text="",
                    element_attributes=None
                ),
                timestamp="2024-12-16T10:00:40Z"
            ),
        ]
    )
